/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogolem_core_FFEngineWrapper */

#ifndef _Included_org_ogolem_core_FFEngineWrapper
#define _Included_org_ogolem_core_FFEngineWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ogolem_core_FFEngineWrapper_serialVersionUID
#define org_ogolem_core_FFEngineWrapper_serialVersionUID 20101108LL
#undef org_ogolem_core_FFEngineWrapper_DEBUG
#define org_ogolem_core_FFEngineWrapper_DEBUG 0L
/*
 * Class:     org_ogolem_core_FFEngineWrapper
 * Method:    CalculateGeomEnergy
 * Signature: (JII[S[DI[D[I)D
 */
JNIEXPORT jdouble JNICALL Java_org_ogolem_core_FFEngineWrapper_CalculateGeomEnergy
  (JNIEnv *, jobject, jlong, jint, jint, jshortArray, jdoubleArray, jint, jdoubleArray, jintArray);

/*
 * Class:     org_ogolem_core_FFEngineWrapper
 * Method:    CalculateGeomGradient
 * Signature: (JII[S[D[DI[D[I)D
 */
JNIEXPORT jdouble JNICALL Java_org_ogolem_core_FFEngineWrapper_CalculateGeomGradient
  (JNIEnv *, jobject, jlong, jint, jint, jshortArray, jdoubleArray, jdoubleArray, jint, jdoubleArray, jintArray);

/*
 * Class:     org_ogolem_core_FFEngineWrapper
 * Method:    OptimiseGeomComplete
 * Signature: (I[S[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_ogolem_core_FFEngineWrapper_OptimiseGeomComplete
  (JNIEnv *, jobject, jint, jshortArray, jdoubleArray);

/*
 * Class:     org_ogolem_core_FFEngineWrapper
 * Method:    OptimiseMolComplete
 * Signature: (I[S[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_ogolem_core_FFEngineWrapper_OptimiseMolComplete
  (JNIEnv *, jobject, jint, jshortArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
