/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ogolem_adaptive_GenericNativeCaller */

#ifndef _Included_org_ogolem_adaptive_GenericNativeCaller
#define _Included_org_ogolem_adaptive_GenericNativeCaller
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ogolem_adaptive_GenericNativeCaller_serialVersionUID
#define org_ogolem_adaptive_GenericNativeCaller_serialVersionUID 20180617LL
/*
 * Class:     org_ogolem_adaptive_GenericNativeCaller
 * Method:    initialize
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ogolem_adaptive_GenericNativeCaller_initialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ogolem_adaptive_GenericNativeCaller
 * Method:    fitnessScalar
 * Signature: (JI[DIJ)D
 */
JNIEXPORT jdouble JNICALL Java_org_ogolem_adaptive_GenericNativeCaller_fitnessScalar
  (JNIEnv *, jclass, jlong, jint, jdoubleArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
